import Logo from "@/components/shared/logo";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Epilogue as FontSans } from "next/font/google";
import React from "react";
import "../globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuhtLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("font-sans bg-whitish-lite dark:bg-dark-bg", fontSans.variable)}
      >
        <div className="p-6 lg:p-10 relative w-full min-h-screen flex items-center justify-center overflow-hidden isolate">
          <Logo className="inline-block absolute top-6 left-6 lg:top-10 lg:left-10 w-10 h-10 lg:w-[52px] lg:h-[52px]" />
          <div className="hidden z-10 lg:block absolute bg-secondary-400/5 dark:bg-primary-500/5 w-[2838px] h-[2838px] rounded-full top-[528px] -left-[418px]" />
          {children}
        </div>
      </body>
    </html>
  );
}
